import Head from 'next/head'
// link
import Link from 'next/link'
import style from '@/styles/Home.module.css'
// components
import Card from '@/components/card'
// imgs
import Image from 'next/image'

import Pngegg from "@/assets/img/pngegg (17) 1.png"

export default function Home() {
  const data = [
    {title: "Test 1",
    description: "Lorem 1"},
    {title: "Test 2",
    description: "Lorem 2"},
    {title: "Test 3",
    description: "Lorem 3"}]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={style.hero}>
          <h1 className={style.hero__title}>Xiaomi Mi Electric Scooter Essential Black</h1>
          <p className={style.hero__text}>
            Lorem ipsum dolor sit amet consectetur. Venenatis est lobortis commodo amet 
            a ultrices. Aliquet dictum nisl natoque viverra platea blandit ac.
           </p>
          <button className={style.hero__btn}>Детальніше</button>
          <Image className={style.hero__bg} src={Pngegg} alt=''></Image>
        </section>
        <section className=''>

        </section>
      </main>
    </>
  )
}