import Head from 'next/head'
// link
import Link from 'next/link'
import style from '@/styles/Home.module.css'
// components
import Card from '@/components/card'
import Form from '@/components/form'
// imgs
import Image from 'next/image'

import Pngegg from "@/assets/img/pngegg (17) 1.png"
import Pngegg_1 from "@/assets/img/pngegg (20) 1.png"
import Pngegg_2 from "@/assets/img/pngegg (19).png"
import Group from "@/assets/img/Group.png"
import Logo from "@/assets/img/logo.png"

import Map from "@/assets/img/карти.png"
import Location from "@/assets/img/Location.png"
import Call from "@/assets/img/Call main.png"
import Time from "@/assets/img/Time Circle main.png"

import FB from "@/assets/img/Vector contacts.png"
import TG from "@/assets/img/Subtract contacts.png"
import INST from "@/assets/img/Group 3 contacts.png"

export default function Home() {
  const data = [
    {title: "Test 1",
    description: "Lorem 1"},
    {title: "Test 2",
    description: "Lorem 2"},
    {title: "Test 3",
    description: "Lorem 3"}]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={style.hero}>
          <h1 className={style.hero__title}>Xiaomi Mi Electric Scooter Essential Black</h1>
          <p className={style.hero__text}>
            Lorem ipsum dolor sit amet consectetur. Venenatis est lobortis commodo amet 
            a ultrices. Aliquet dictum nisl natoque viverra platea blandit ac.
           </p>
          <button className={style.hero__btn}>Детальніше</button>
          <Image className={style.hero__bg} src={Pngegg} alt=''></Image>
        </section>
        <section className={style.goods}>
          <div className={style.goods__categories}>
            <h1 className={style.goods__categories_item}>Зброя</h1>
            <div className={style.goods__categories_line}></div>
            <h1 className={style.goods__categories_item}>Техніка</h1>
            <div className={style.goods__categories_line}></div>
            <h1 className={style.goods__categories_item_active}>Електросамокати</h1>
            <div className={style.goods__categories_line}></div>
            <h1 className={style.goods__categories_item}>Популярне</h1>
            <div className={style.goods__categories_line}></div>
            <h1 className={style.goods__categories_item}>Акції</h1>
          </div>
          <div className={style.goods__cart}>
            <Card key={"testKey"} title='Xiaomi Mi Electric Scooter' description='Швидкість > 20 км/г' id='test'></Card>
            <Card key={"testKey"} title='Xiaomi Mi Electric Scooter Essential Black' description='19 000 ₴' id='test'></Card>
            <Card key={"testKey"} title='Xiaomi Mi Electric Scooter' description='Швидкість > 20 км/г' id='test'></Card>
            <Card key={"testKey"} title='Xiaomi Mi Electric Scooter Essential Black' description='19 000 ₴' id='test'></Card>
            <Card key={"testKey"} title='Xiaomi Mi Electric Scooter' description='Швидкість > 20 км/г' id='test'></Card>
            <Card key={"testKey"} title='Xiaomi Mi Electric Scooter Essential Black' description='19 000 ₴' id='test'></Card>
            <Card key={"testKey"} title='Xiaomi Mi Electric Scooter' description='Швидкість > 20 км/г' id='test'></Card>
            <Card key={"testKey"} title='Xiaomi Mi Electric Scooter Essential Black' description='19 000 ₴' id='test'></Card>
            <Card key={"testKey"} title='Xiaomi Mi Electric Scooter' description='Швидкість > 20 км/г' id='test'></Card>
            <Card key={"testKey"} title='Xiaomi Mi Electric Scooter Essential Black' description='19 000 ₴' id='test'></Card>
            <Card key={"testKey"} title='Xiaomi Mi Electric Scooter' description='Швидкість > 20 км/г' id='test'></Card>
            <Card key={"testKey"} title='Xiaomi Mi Electric Scooter Essential Black' description='19 000 ₴' id='test'></Card>
          </div>
        </section>
        <section className={style.special_offer}>
          <Image className={style.special_offer__img} src={Pngegg_2} alt=''></Image>
          <h1 className={style.special_offer__title}>Xiaomi Mi Electric Scooter Essential Black</h1>
          <div className={style.special_offer__prices}>
            <h2 className={style.special_offer__prices_old}>19 000 ₴</h2>
            <h2 className={style.special_offer__prices_new}>16 999 ₴</h2>
          </div>
          <button className={style.special_offer__btn}>Детальніше</button>
        </section>
        <section className={style.recommended}>
          <h1 className={style.recommended__title}>Рекомендовані товари</h1>
          <div className={style.recommended__line}></div>
          <div className={style.recommended__goods}>
            <Card key={"testKey"} title='Xiaomi Mi Electric Scooter' description='Швидкість > 20 км/г' id='test'></Card>
            <Card key={"testKey"} title='Xiaomi Mi Electric Scooter Essential Black' description='19 000 ₴' id='test'></Card>
            <Card key={"testKey"} title='Xiaomi Mi Electric Scooter' description='Швидкість > 20 км/г' id='test'></Card>
            <Card key={"testKey"} title='Xiaomi Mi Electric Scooter Essential Black' description='19 000 ₴' id='test'></Card>
          </div>
        </section>
        <section className={style.brandmark}>
          <h1 className={style.brandmark__title}>Торгові марки</h1>
          <div className={style.brandmark__line}></div>
          <div className={style.brandmark__logos}>
            <Image className={style.brandmark__logos_fisrst} src={Group} alt=''></Image>
            <Image className={style.brandmark__logos_second} src={Logo} alt=''></Image>
            <Image className={style.brandmark__logos_fisrst} src={Group} alt=''></Image>
            <Image className={style.brandmark__logos_second} src={Logo} alt=''></Image>
            <Image className={style.brandmark__logos_fisrst} src={Group} alt=''></Image>
            <Image className={style.brandmark__logos_second} src={Logo} alt=''></Image>
            <Image className={style.brandmark__logos_fisrst} src={Group} alt=''></Image>
          </div>
        </section>
        <Form></Form>
        <section className={style.location}>
          <Image className={style.location__map} src={Map} alt=''></Image>
          <div className={style.location__contacts}>
            <h1 className={style.location__contacts_title}>Контакти</h1>
            <div className={style.location__contacts_box}>
              <Image className={style.location__contacts_box_img} src={Call} alt=''></Image>
              <h2 className={style.location__contacts_box_text}>093 005 37 93</h2>
            </div>
            <div className={style.location__contacts_box}>
              <Image className={style.location__contacts_box_img} src={Time} alt=''></Image>
              <h2 className={style.location__contacts_box_text}>10:00 - 20:00</h2>
            </div>
            <div className={style.location__contacts_box}>
              <Image className={style.location__contacts_box_img} src={Location} alt=''></Image>
              <h2 className={style.location__contacts_box_text}>вул. Трускавецька 50</h2>
            </div>
            <ul className={style.location__contacts_list}>
              <li><Link href="/"><Image className={style.location__contacts_list_item} src={FB} alt=""></Image></Link></li>
              <li><Link href="/"><Image className={style.location__contacts_list_item} src={TG} alt=""></Image></Link></li>
              <li><Link href="/"><Image className={style.location__contacts_list_item} src={INST} alt=""></Image></Link></li>
            </ul>
          </div>
        </section>
      </main>
    </>
  )
}