import Head from 'next/head'
// link
import Link from 'next/link'
import style from '@/styles/Home.module.css'
// components
import Card from '@/components/card'
// imgs
import Image from 'next/image'

import Pngegg from "@/assets/img/pngegg (17) 1.png"
import Pngegg_1 from "@/assets/img/pngegg (20) 1.png"
import Pngegg_2 from "@/assets/img/pngegg (19).png"

export default function Home() {
  const data = [
    {title: "Test 1",
    description: "Lorem 1"},
    {title: "Test 2",
    description: "Lorem 2"},
    {title: "Test 3",
    description: "Lorem 3"}]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={style.hero}>
          <h1 className={style.hero__title}>Xiaomi Mi Electric Scooter Essential Black</h1>
          <p className={style.hero__text}>
            Lorem ipsum dolor sit amet consectetur. Venenatis est lobortis commodo amet 
            a ultrices. Aliquet dictum nisl natoque viverra platea blandit ac.
           </p>
          <button className={style.hero__btn}>Детальніше</button>
          <Image className={style.hero__bg} src={Pngegg} alt=''></Image>
        </section>
        <section className={style.goods}>
          <div className={style.goods__categories}>
            <h1 className={style.goods__categories_item}>Зброя</h1>
            <div className={style.goods__categories_line}></div>
            <h1 className={style.goods__categories_item}>Техніка</h1>
            <div className={style.goods__categories_line}></div>
            <h1 className={style.goods__categories_item_active}>Електросамокати</h1>
            <div className={style.goods__categories_line}></div>
            <h1 className={style.goods__categories_item}>Популярне</h1>
            <div className={style.goods__categories_line}></div>
            <h1 className={style.goods__categories_item}>Акції</h1>
          </div>
          <div className={style.goods__cart}>
            <div className={style.goods__cart_item}>
              <Image className={style.goods__cart_item_img} src={Pngegg_1} alt=''></Image>
              <h1 className={style.goods__cart_item_title}>Xiaomi Mi Electric Scooter Essential Black</h1>
              <p className={style.goods__cart_item_text}>19 000 ₴</p>
              <button className={style.goods__cart_item_btn}>Купити</button>
            </div>
            <div className={style.goods__cart_item}>
              <Image className={style.goods__cart_item_img} src={Pngegg_1} alt=''></Image>
              <h1 className={style.goods__cart_item_title}>Xiaomi Mi Electric Scooter Essential Black</h1>
              <p className={style.goods__cart_item_text}>19 000 ₴</p>
              <button className={style.goods__cart_item_btn}>Купити</button>
            </div>
            <div className={style.goods__cart_item}>
              <Image className={style.goods__cart_item_img} src={Pngegg_1} alt=''></Image>
              <h1 className={style.goods__cart_item_title}>Xiaomi Mi Electric Scooter Essential Black</h1>
              <p className={style.goods__cart_item_text}>19 000 ₴</p>
              <button className={style.goods__cart_item_btn}>Купити</button>
            </div>
            <div className={style.goods__cart_item}>
              <Image className={style.goods__cart_item_img} src={Pngegg_1} alt=''></Image>
              <h1 className={style.goods__cart_item_title}>Xiaomi Mi Electric Scooter Essential Black</h1>
              <p className={style.goods__cart_item_text}>19 000 ₴</p>
              <button className={style.goods__cart_item_btn}>Купити</button>
            </div>
            <div className={style.goods__cart_item}>
              <Image className={style.goods__cart_item_img} src={Pngegg_1} alt=''></Image>
              <h1 className={style.goods__cart_item_title}>Xiaomi Mi Electric Scooter Essential Black</h1>
              <p className={style.goods__cart_item_text}>19 000 ₴</p>
              <button className={style.goods__cart_item_btn}>Купити</button>
            </div>
            <div className={style.goods__cart_item}>
              <Image className={style.goods__cart_item_img} src={Pngegg_1} alt=''></Image>
              <h1 className={style.goods__cart_item_title}>Xiaomi Mi Electric Scooter Essential Black</h1>
              <p className={style.goods__cart_item_text}>19 000 ₴</p>
              <button className={style.goods__cart_item_btn}>Купити</button>
            </div>
            <div className={style.goods__cart_item}>
              <Image className={style.goods__cart_item_img} src={Pngegg_1} alt=''></Image>
              <h1 className={style.goods__cart_item_title}>Xiaomi Mi Electric Scooter Essential Black</h1>
              <p className={style.goods__cart_item_text}>19 000 ₴</p>
              <button className={style.goods__cart_item_btn}>Купити</button>
            </div>
            <div className={style.goods__cart_item}>
              <Image className={style.goods__cart_item_img} src={Pngegg_1} alt=''></Image>
              <h1 className={style.goods__cart_item_title}>Xiaomi Mi Electric Scooter Essential Black</h1>
              <p className={style.goods__cart_item_text}>19 000 ₴</p>
              <button className={style.goods__cart_item_btn}>Купити</button>
            </div>
          </div>
        </section>
        <section className={style.special_offer}>
          <Image className={style.special_offer__img} src={Pngegg_2} alt=''></Image>
          <h1 className={style.special_offer__title}>Xiaomi Mi Electric Scooter Essential Black</h1>
          <div className={style.special_offer__prices}>
            <h2 className={style.special_offer__prices_old}>19 000 ₴</h2>
            <h2 className={style.special_offer__prices_new}>16 999 ₴</h2>
          </div>
          <button className={style.special_offer__btn}>Детальніше</button>
        </section>
        <form className={style.form}>
          <h1 className={style.form__title}>Виникли запитання?</h1>
          <input className={style.form__name} type="text" placeholder='Ваше ім’я'/>
          <input className={style.form__phone} type="text" placeholder='Номер телефону'/>
          <label className={style.form__label} htmlFor="submit">Залиште заявку і ми Вам передзвонимо</label>
          <button className={style.form__submit} type="submit" name='submit'>Надіслати</button>
        </form>
      </main>
    </>
  )
}